apiVersion: monitoring.rhobs/v1
kind: Prometheus
metadata:
  name: metric-storage
  namespace: openstack
spec:
  #  listenLocal: true
  containers:
  - name: kube-rbac-proxy
    image: quay.io/brancz/kube-rbac-proxy:v0.16.0
    args:
    - "--secure-listen-address=0.0.0.0:8443"
    - "--upstream=http://127.0.0.1:9090/"
    - "--logtostderr=true"
    - "--v=10"
    - "--tls-cert-file=/etc/tls/private/tls.crt"
    - "--tls-private-key-file=/etc/tls/private/tls.key"
    ports:
      - containerPort: 8443
        name: https
        protocol: TCP
    volumeMounts:
      - mountPath: /etc/tls/private
        name: secret-cert-metric-storage-prometheus-proxy-svc
      - mountPath: /etc/client
        name: secret-cert-client
  secrets:
    - 'cert-metric-storage-prometheus-proxy-svc'
    - 'cert-client'
