apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    owner: ceilometer
    service: ceilometer
  name: ceilometer
  namespace: openstack
spec:
  template:
    spec:
      containers:
      - name: kube-rbac-proxy
        image: quay.io/brancz/kube-rbac-proxy:v0.16.0
        args:
        - "--secure-listen-address=0.0.0.0:8443"
        - "--upstream=http://127.0.0.1:3001/"
        - "--logtostderr=true"
        - "--v=10"
        - "--tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
        - "--tls-cert-file=/etc/tls/private/tls.crt"
        - "--tls-private-key-file=/etc/tls/private/tls.key"
        - "--client-ca-file=/etc/client/ca.crt"
        ports:
          - containerPort: 8443
            name: https
            protocol: TCP
        volumeMounts:
          - mountPath: /etc/tls/private
            name: cert-ceilometer-proxy-svc
          - mountPath: /etc/client
            name: cert-client
      volumes:
      - name: cert-ceilometer-proxy-svc
        secret:
          defaultMode: 420
          secretName: cert-ceilometer-proxy-svc
      - name: cert-client
        secret:
          defaultMode: 420
          secretName: cert-client
